In [37]:
import numpy as np
import pandas as pd

In [38]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [39]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [40]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [41]:
movies = movies.merge(credits, on = 'title')

In [42]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

In [43]:
# genere, id, keywords, title, overview, cast, crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [44]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [45]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [46]:
movies.dropna(inplace=True)

In [47]:
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [48]:
movies.duplicated().sum()

0

In [49]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [12]:
#'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
# to ['Action', 'Adventure'.....]

In [50]:
def convert (obj):
    L = []
    for i in obj:
        L.append(i['name'])
    return L

In [51]:
convert(movies.iloc[0].genres)

TypeError: string indices must be integers, not 'str'

In [54]:
import ast
#using literal eval funtion to convert string to list
ast.literal_eval(movies.iloc[0].genres)

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [55]:
def convert (obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [57]:
movies['genres'] = movies['genres'].apply(convert)

ValueError: malformed node or string: ['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [58]:
movies

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...,"[Action, Crime, Thriller]","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...,"[Comedy, Romance]",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic...","[Comedy, Drama, Romance, TV Movie]","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...,[Documentary],"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [59]:
movies['keywords'] = movies['keywords'].apply(convert)

In [60]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [61]:
#extracting top 3 actor names
def convert2 (obj):
    L = []
    cnt=0;
    for i in ast.literal_eval(obj):
        if(cnt==3):
            break;
        else:
            L.append(i['name'])
            cnt+=1
    return L

In [62]:
movies['cast'] = movies['cast'].apply(convert2)

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [63]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break;
    return L

In [64]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [65]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [66]:
# overview is still a string we want to convert it to a list as well
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [67]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [81]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [28]:
# We now want to remove spaces between names to avoid confusion in 
movies['genres'] = movies['genres'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x:[i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x:[i.replace(" ", "") for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [68]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [69]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [70]:
new_df = movies[['movie_id', 'title', 'tags']]

In [32]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [71]:
# converting the list: tags to string
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13948\662184663.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [34]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [72]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy Science Fiction culture clash future space war space colony society space travel futuristic romance space alien tribe alien planet cgi marine soldier battle love affair anti war power relations mind and soul 3d Sam Worthington Zoe Saldana Sigourney Weaver James Cameron'

In [92]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12372\1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [73]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

Vectorization

In [74]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [75]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [76]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [77]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [78]:
# do steming for similar words
#[ love, loved, loving] = [love, love, love]

import nltk

In [79]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [80]:
def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

In [81]:
#examples of stemming
ps.stem('dancing')

'danc'

In [82]:
new_df['tags'] = new_df['tags'].apply(stem)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_13948\3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [83]:
new_df['tags']

0       in the 22nd century, a parapleg marin is dispa...
1       captain barbossa, long believ to be dead, ha c...
2       a cryptic messag from bond’ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a war-weary, former militari ca...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw couple' honeymoon is upend by the arr...
4806    "signed, sealed, delivered" introduc a dedic q...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [84]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [85]:
cv.get_feature_names_out()

array(['000', '007', '10', ..., 'zooey', 'zucker', 'zwick'], dtype=object)

In [86]:
 #cosine distance
from sklearn.metrics.pairwise import cosine_similarity

In [87]:
#4806x4806 matrix with each row suggesting the similarity of a movie with others
similarity = cosine_similarity(vectors)

In [89]:
similarity[0]
# we want to pair the similarity with index then sort
list(enumerate(similarity[0])) # this tells 0 index movie ka har movie index sath similarity

[(0, 0.9999999999999998),
 (1, 0.06692744814102546),
 (2, 0.06554735253444621),
 (3, 0.04335549847620599),
 (4, 0.28791446098121787),
 (5, 0.1433848336691011),
 (6, 0.035121967934313526),
 (7, 0.11654330934961299),
 (8, 0.03771571432023571),
 (9, 0.10036938356837077),
 (10, 0.11029436104106954),
 (11, 0.07733602811121824),
 (12, 0.054410718758250876),
 (13, 0.024738534799764667),
 (14, 0.1577233170360112),
 (15, 0.06855106213838522),
 (16, 0.10366105360784114),
 (17, 0.108147614087175),
 (18, 0.13006649542861798),
 (19, 0.06855106213838522),
 (20, 0.05528134553975607),
 (21, 0.06362847629757777),
 (22, 0.04415107856883479),
 (23, 0.05309942440535914),
 (24, 0.04518564248465834),
 (25, 0.06309151753013043),
 (26, 0.16427061504961218),
 (27, 0.20519567041703077),
 (28, 0.06955186050933215),
 (29, 0.052288698561600205),
 (30, 0.09809657456746182),
 (31, 0.14808721943977307),
 (32, 0.07894736842105261),
 (33, 0.09558988911273406),
 (34, 0.0),
 (35, 0.1675415633166782),
 (36, 0.15897016107942194),
 (37, 0.08549819600709618),
 (38, 0.06494054168326638),
 (39, 0.09453802374948816),
 (40, 0.04682929057908469),
 (41, 0.21341639745917707),
 (42, 0.0),
 (43, 0.08812102431690699),
 (44, 0.03771571432023571),
 (45, 0.06578947368421051),
 (46, 0.17013926184468012),
 (47, 0.2987264917430253),
 (48, 0.09959431881428263),
 (49, 0.03877833671647406),
 (50, 0.07079923254047886),
 (51, 0.09895413919905867),
 (52, 0.22790142204853647),
 (53, 0.11764957176360046),
 (54, 0.01938916835823703),
 (55, 0.04499212706658475),
 (56, 0.24722569302909875),
 (57, 0.06302534916632545),
 (58, 0.045580284409707295),
 (59, 0.054437944538667765),
 (60, 0.011357771260606367),
 (61, 0.25958499574503335),
 (62, 0.04891159880445184),
 (63, 0.08285522649991611),
 (64, 0.064888568452305),
 (65, 0.042601432284230495),
 (66, 0.014451832825401996),
 (67, 0.1946978894863169),
 (68, 0.07733602811121824),
 (69, 0.026871538646250696),
 (70, 0.11712303424679454),
 (71, 0.08193419066805777),
 (72, 0.12725695259515554),
 (73, 0.01911797782254681),
 (74, 0.24678382369818674),
 (75, 0.08456376143646728),
 (76, 0.06424925662032355),
 (77, 0.01981850088223545),
 (78, 0.030934411244487297),
 (79, 0.07894736842105261),
 (80, 0.028878211074619464),
 (81, 0.07950439882424458),
 (82, 0.08031157077540443),
 (83, 0.22213082915965962),
 (84, 0.074215604399294),
 (85, 0.08017658293783157),
 (86, 0.08549819600709618),
 (87, 0.17099639201419237),
 (88, 0.04598545046137244),
 (89, 0.04730472703803727),
 (90, 0.03627381250550058),
 (91, 0.20991342856239587),
 (92, 0.04204138910034078),
 (93, 0.05691103932244722),
 (94, 0.2866297455600074),
 (95, 0.25362863675089403),
 (96, 0.06622661785325219),
 (97, 0.07530940414109723),
 (98, 0.04966996338993915),
 (99, 0.015193428136569098),
 (100, 0.07024393586862705),
 (101, 0.1541517600345829),
 (102, 0.11764957176360048),
 (103, 0.08226127456606226),
 (104, 0.046401616866730944),
 (105, 0.09068453126375145),
 (106, 0.05162257329196673),
 (107, 0.1106817677872384),
 (108, 0.1615552112476628),
 (109, 0.056573571480353566),
 (110, 0.1361331925293325),
 (111, 0.17497830981833887),
 (112, 0.08111071056538126),
 (113, 0.027036903521793755),
 (114, 0.027226638505866502),
 (115, 0.05564148840746572),
 (116, 0.045580284409707295),
 (117, 0.030386856273138196),
 (118, 0.021030505843376807),
 (119, 0.06716604942594676),
 (120, 0.0),
 (121, 0.0734718358370645),
 (122, 0.09304036594559835),
 (123, 0.09464970485606018),
 (124, 0.07530940414109723),
 (125, 0.08433490104000932),
 (126, 0.07530940414109723),
 (127, 0.14429582107316452),
 (128, 0.03498557142706597),
 (129, 0.09334163073596637),
 (130, 0.014013796366780261),
 (131, 0.08849904067559858),
 (132, 0.04204138910034078),
 (133, 0.03121952705272313),
 (134, 0.07647191129018724),
 (135, 0.0),
 (136, 0.015328483487124145),
 (137, 0.020602141085758228),
 (138, 0.11969747440993465),
 (139, 0.07836039099693788),
 (140, 0.041427613249958056),
 (141, 0.16556654463313047),
 (142, 0.05073825686188037),
 (143, 0.07894736842105261),
 (144, 0.07295405746286962),
 (145, 0.07690914705058355),
 (146, 0.05518884821104349),
 (147, 0.11243619908556621),
 (148, 0.05510387687779837),
 (149, 0.2896811091620759),
 (150, 0.22941573387056172),
 (151, 0.12540051368250324),
 (152, 0.04916051440083466),
 (153, 0.0519524333466131),
 (154, 0.03721614637823934),
 (155, 0.025811286645983363),
 (156, 0.14975189244419534),
 (157, 0.06083303292403594),
 (158, 0.3222129681246328),
 (159, 0.056573571480353566),
 (160, 0.07455250649740336),
 (161, 0.059016710652347516),
 (162, 0.059016710652347516),
 (163, 0.06759225880448438),
 (164, 0.05247835714059896),
 (165, 0.056055185467121044),
 (166, 0.10259783520851543),
 (167, 0.059016710652347516),
 (168, 0.19664205760333864),
 (169, 0.1343320988518935),
 (170, 0.08408277820068157),
 (171, 0.04518564248465834),
 (172, 0.11589658124319133),
 (173, 0.031814238148788886),
 (174, 0.09597148699373931),
 (175, 0.04335549847620599),
 (176, 0.014227759830611805),
 (177, 0.021677749238102995),
 (178, 0.016062314155080887),
 (179, 0.04415107856883479),
 (180, 0.013518451760896878),
 (181, 0.02649064714130087),
 (182, 0.08346223261119859),
 (183, 0.05651250986355305),
 (184, 0.30842358510917445),
 (185, 0.10926834468453095),
 (186, 0.043550355630934214),
 (187, 0.10147651372376074),
 (188, 0.047836487323493986),
 (189, 0.07175473098524097),
 (190, 0.06759225880448438),
 (191, 0.04370374100610487),
 (192, 0.08536655898367082),
 (193, 0.06503324771430899),
 (194, 0.015193428136569098),
 (195, 0.051298917604257706),
 (196, 0.07953559537197222),
 (197, 0.05979560915436748),
 (198, 0.03346372407051273),
 (199, 0.06494054168326638),
 (200, 0.16122923187750418),
 (201, 0.01967223688411584),
 (202, 0.018857857160117855),
 (203, 0.08549819600709618),
 (204, 0.028027592733560522),
 (205, 0.03934447376823168),
 (206, 0.1032370802417528),
 (207, 0.12519334891679787),
 (208, 0.12361284651454937),
 (209, 0.03458572319330373),
 (210, 0.07059781184061312),
 (211, 0.04598545046137244),
 (212, 0.04634897746593215),
 (213, 0.05853661322385588),
 (214, 0.0),
 (215, 0.11470786693528086),
 (216, 0.03877833671647406),
 (217, 0.09334163073596637),
 (218, 0.023918243661746993),
 (219, 0.07543142864047142),
 (220, 0.13109470506889243),
 (221, 0.032124628310161774),
 (222, 0.15806712450288418),
 (223, 0.16556654463313047),
 (224, 0.06855106213838522),
 (225, 0.04370374100610487),
 (226, 0.07755667343294811),
 (227, 0.07804881763180782),
 (228, 0.20073876713674155),
 (229, 0.1538057703910978),
 (230, 0.20441907985364974),
 (231, 0.02845551966122361),
 (232, 0.13834289277321493),
 (233, 0.17040572913692198),
 (234, 0.06622661785325218),
 (235, 0.04818694246524266),
 (236, 0.20561572340611634),
 (237, 0.03877833671647406),
 (238, 0.09131087488821056),
 (239, 0.2752988806446741),
 (240, 0.028027592733560522),
 (241, 0.04966996338993915),
 (242, 0.06024752331287778),
 (243, 0.0512989176042577),
 (244, 0.048666426339228755),
 (245, 0.04173111630559929),
 (246, 0.09673016668133488),
 (247, 0.0),
 (248, 0.026669037353133248),
 (249, 0.17040572913692198),
 (250, 0.0),
 (251, 0.07336739820667776),
 (252, 0.011831213107007523),
 (253, 0.09895413919905867),
 (254, 0.044060512158453496),
 (255, 0.0),
 (256, 0.11470786693528087),
 (257, 0.04268327949183541),
 (258, 0.023537557657892522),
 (259, 0.032124628310161774),
 (260, 0.29135827337403253),
 (261, 0.04204138910034078),
 (262, 0.07404360971988654),
 (263, 0.055824219567359015),
 (264, 0.0),
 (265, 0.016912752287293456),
 (266, 0.07596714068284549),
 (267, 0.12695834376925202),
 (268, 0.028903665650803993),
 (269, 0.016062314155080887),
 (270, 0.20138310507789547),
 (271, 0.09637388493048532),
 (272, 0.018857857160117855),
 (273, 0.009304036594559835),
 (274, 0.05887552214709278),
 (275, 0.11969747440993464),
 (276, 0.03498557142706597),
 (277, 0.03568395510523548),
 (278, 0.3311330892662609),
 (279, 0.1251933489167979),
 (280, 0.0),
 (281, 0.03668369910333888),
 (282, 0.03587736549262049),
 (283, 0.012824729401064425),
 (284, 0.012667364798453496),
 (285, 0.012667364798453496),
 (286, 0.06653536832815835),
 (287, 0.014933692277237473),
 (288, 0.016731862035256364),
 (289, 0.03065696697424829),
 (290, 0.03582871819500093),
 (291, 0.06424925662032355),
 (292, 0.06622661785325219),
 (293, 0.016556654463313048),
 (294, 0.09428928580058928),
 (295, 0.06362847629757777),
 (296, 0.03627381250550058),
 (297, 0.05691103932244722),
 (298, 0.0),
 (299, 0.0468292905790847),
 (300, 0.32481131806711666),
 (301, 0.08511306704001456),
 (302, 0.04818694246524266),
 (303, 0.015609763526361564),
 (304, 0.09154684414630487),
 (305, 0.3421708589084696),
 (306, 0.17914359097500465),
 (307, 0.09308574042571362),
 (308, 0.03419927840283847),
 (309, 0.03993615319154359),
 (310, 0.017292861596651866),
 (311, 0.1113498335207611),
 (312, 0.09365858115816939),
 (313, 0.03382550457458691),
 (314, 0.0),
 (315, 0.05374307729250139),
 (316, 0.038474188203193274),
 (317, 0.042601432284230495),
 (318, 0.0),
 (319, 0.08520286456846099),
 (320, 0.08849904067559858),
 (321, 0.0),
 (322, 0.2533558548547658),
 (323, 0.03721614637823934),
 (324, 0.016731862035256364),
 (325, 0.05247835714059896),
 (326, 0.05073825686188037),
 (327, 0.031814238148788886),
 (328, 0.02597621667330655),
 (329, 0.10259783520851541),
 (330, 0.10039117221153819),
 (331, 0.06667259338283311),
 (332, 0.08111071056538126),
 (333, 0.08111071056538126),
 (334, 0.09280323373346189),
 (335, 0.058271654674806495),
 (336, 0.029135827337403247),
 (337, 0.07466846138618737),
 (338, 0.03934447376823168),
 (339, 0.04726901187474408),
 (340, 0.033113308926626096),
 (341, 0.08365931017628181),
 (342, 0.21371260356627755),
 (343, 0.01141385936102632),
 (344, 0.017914359097500464),
 (345, 0.015467205622243648),
 (346, 0.016912752287293456),
 (347, 0.0324442842261525),
 (348, 0.03877833671647406),
 (349, 0.048666426339228755),
 (350, 0.04682929057908469),
 (351, 0.0),
 (352, 0.01860807318911967),
 (353, 0.05098127419345816),
 (354, 0.013157894736842103),
 (355, 0.032961063021678665),
 (356, 0.05374307729250139),
 (357, 0.0),
 (358, 0.05374307729250139),
 (359, 0.01911797782254681),
 (360, 0.08326256191221612),
 (361, 0.046401616866730944),
 (362, 0.12105003117656304),
 (363, 0.11764957176360048),
 (364, 0.014451832825401996),
 (365, 0.13685996549319585),
 (366, 0.06554735253444621),
 (367, 0.0),
 (368, 0.07647191129018724),
 (369, 0.07059781184061312),
 (370, 0.064888568452305),
 (371, 0.10635399695598369),
 (372, 0.06243905410544626),
 (373, 0.380442955126341),
 (374, 0.025334729596906993),
 (375, 0.07059781184061312),
 (376, 0.04370374100610487),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0549351050361311),
 (380, 0.03065696697424829),
 (381, 0.0512989176042577),
 (382, 0.0),
 (383, 0.026315789473684206),
 (384, 0.029135827337403247),
 (385, 0.03539961627023943),
 (386, 0.012905643322991682),
 (387, 0.013157894736842103),
 (388, 0.0),
 (389, 0.11020775375559674),
 (390, 0.03382550457458691),
 (391, 0.06917144638660747),
 (392, 0.016912752287293456),
 (393, 0.015193428136569098),
 (394, 0.014567913668701624),
 (395, 0.05298129428260174),
 (396, 0.026851080677052733),
 (397, 0.03346372407051273),
 (398, 0.0),
 (399, 0.014808721943977306),
 (400, 0.10039117221153819),
 (401, 0.15058675831730728),
 (402, 0.045580284409707295),
 (403, 0.0604563541758343),
 (404, 0.10259783520851541),
 (405, 0.026669037353133248),
 (406, 0.026144349280800103),
 (407, 0.06131393394849658),
 (408, 0.01911797782254681),
 (409, 0.0),
 (410, 0.06282808624375431),
 (411, 0.046401616866730944),
 (412, 0.10280786170305815),
 (413, 0.10926834468453095),
 (414, 0.018367958959266125),
 (415, 0.05348281873006976),
 (416, 0.04518564248465834),
 (417, 0.03673591791853225),
 (418, 0.0899842541331695),
 (419, 0.11846977555181845),
 (420, 0.1007265930331758),
 (421, 0.012369267399882334),
 (422, 0.10375716957991118),
 (423, 0.05407380704358751),
 (424, 0.024738534799764667),
 (425, 0.048098607024388174),
 (426, 0.06653536832815836),
 (427, 0.018857857160117855),
 (428, 0.05395404209689377),
 (429, 0.0),
 (430, 0.1216660658480719),
 (431, 0.015061880828219446),
 (432, 0.2364763257317293),
 (433, 0.01911797782254681),
 (434, 0.0),
 (435, 0.019968076595771794),
 (436, 0.016386838133611553),
 (437, 0.017292861596651866),
 (438, 0.09453802374948816),
 (439, 0.04818694246524266),
 (440, 0.015061880828219446),
 (441, 0.05309942440535914),
 (442, 0.036893922595746136),
 (443, 0.048636038308579745),
 (444, 0.012824729401064425),
 (445, 0.07466846138618737),
 (446, 0.05647824947249049),
 (447, 0.04235868710436787),
 (448, 0.0805532420311582),
 (449, 0.08957179548750233),
 (450, 0.039735970711951306),
 (451, 0.014933692277237473),
 (452, 0.011707322644771175),
 (453, 0.015193428136569098),
 (454, 0.19619314913492364),
 (455, 0.041130637283031124),
 (456, 0.1290564332299168),
 (457, 0.05510387687779837),
 (458, 0.029867384554474945),
 (459, 0.11314714296070713),
 (460, 0.061868822488974594),
 (461, 0.30442954117128224),
 (462, 0.11024280153951839),
 (463, 0.05990422978731538),
 (464, 0.0),
 (465, 0.022075539284417394),
 (466, 0.17660431427533915),
 (467, 0.07169241683455055),
 (468, 0.017099639201419235),
 (469, 0.07175473098524097),
 (470, 0.04598545046137244),
 (471, 0.06759225880448438),
 (472, 0.08549819600709618),
 (473, 0.13006649542861795),
 (474, 0.0),
 (475, 0.05523681766661074),
 (476, 0.10838874619051497),
 (477, 0.0),
 (478, 0.05468482990747588),
 (479, 0.0604563541758343),
 (480, 0.18074256993863336),
 (481, 0.015328483487124145),
 (482, 0.013518451760896878),
 (483, 0.1399422857082639),
 (484, 0.03771571432023571),
 (485, 0.044426165831931916),
 (486, 0.05213993951603676),
 (487, 0.11980845957463077),
 (488, 0.054437944538667765),
 (489, 0.0),
 (490, 0.13497638119975425),
 (491, 0.08658487179917634),
 (492, 0.06765100914917382),
 (493, 0.02995211489365769),
 (494, 0.020277677641345315),
 (495, 0.12695834376925205),
 (496, 0.023537557657892522),
 (497, 0.0),
 (498, 0.05990422978731538),
 (499, 0.0),
 (500, 0.015193428136569098),
 (501, 0.04634897746593215),
 (502, 0.24165972609347458),
 (503, 0.04682929057908469),
 (504, 0.0),
 (505, 0.13382584475782766),
 (506, 0.08111071056538126),
 (507, 0.3231104224953257),
 (508, 0.07664241743562072),
 (509, 0.014933692277237473),
 (510, 0.08193419066805777),
 (511, 0.07443229275647868),
 (512, 0.06554735253444621),
 (513, 0.08885233166386383),
 (514, 0.025811286645983363),
 (515, 0.0324442842261525),
 (516, 0.014686837386151166),
 (517, 0.05098127419345816),
 (518, 0.044060512158453496),
 (519, 0.0),
 (520, 0.0),
 (521, 0.013809204416652685),
 (522, 0.014933692277237473),
 (523, 0.033113308926626096),
 (524, 0.09637388493048532),
 (525, 0.06077371254627639),
 (526, 0.05564148840746572),
 (527, 0.016912752287293456),
 (528, 0.013809204416652685),
 (529, 0.14599927901768628),
 (530, 0.03721614637823934),
 (531, 0.09397878236968457),
 (532, 0.08918325397005952),
 (533, 0.03934447376823168),
 (534, 0.07694837640638655),
 (535, 0.08740748201220974),
 (536, 0.11654330934961299),
 (537, 0.04415107856883479),
 (538, 0.0),
 (539, 0.27912109783679506),
 (540, 0.045580284409707295),
 (541, 0.24366985862022406),
 (542, 0.03754696307413191),
 (543, 0.047721357223183325),
 (544, 0.032773676267223106),
 (545, 0.044426165831931916),
 (546, 0.04055535528269063),
 (547, 0.05510387687779837),
 (548, 0.014227759830611805),
 (549, 0.23308661869922598),
 (550, 0.015467205622243648),
 (551, 0.023662426214015046),
 (552, 0.0),
 (553, 0.016731862035256364),
 (554, 0.0),
 (555, 0.04008829146891578),
 (556, 0.08193419066805777),
 (557, 0.19918863762856526),
 (558, 0.04966996338993915),
 (559, 0.03877833671647406),
 (560, 0.02305714879553582),
 (561, 0.03627381250550058),
 (562, 0.017292861596651866),
 (563, 0.015756337291581362),
 (564, 0.1630554699247529),
 (565, 0.04335549847620599),
 (566, 0.012905643322991682),
 (567, 0.016062314155080887),
 (568, 0.1183892660110542),
 (569, 0.04598545046137244),
 (570, 0.041204282171516456),
 (571, 0.10705186531570646),
 (572, 0.06622661785325218),
 (573, 0.024318019154289872),
 (574, 0.014227759830611805),
 (575, 0.07169241683455055),
 (576, 0.046401616866730944),
 (577, 0.30588764516074896),
 (578, 0.02488363008967197),
 (579, 0.1749783098183389),
 (580, 0.014338483366910109),
 (581, 0.23288666826750604),
 (582, 0.29314232661238443),
 (583, 0.03568395510523548),
 (584, 0.07336739820667776),
 (585, 0.10729938440986901),
 (586, 0.10012523486435176),
 (587, 0.13809204416652687),
 (588, 0.017292861596651866),
 (589, 0.11615078990692514),
 (590, 0.01911797782254681),
 (591, 0.0645282166149584),
 (592, 0.11615078990692514),
 (593, 0.03668369910333888),
 (594, 0.028239124736245246),
 (595, 0.25387276871303704),
 (596, 0.059234887775909226),
 (597, 0.033113308926626096),
 (598, 0.04415107856883479),
 (599, 0.10814761408717502),
 (600, 0.046401616866730944),
 (601, 0.04055535528269063),
 (602, 0.061868822488974594),
 (603, 0.03065696697424829),
 (604, 0.03877833671647406),
 (605, 0.016386838133611553),
 (606, 0.02282771872205264),
 (607, 0.07336739820667776),
 (608, 0.0),
 (609, 0.04204138910034078),
 (610, 0.0691073690718941),
 (611, 0.058271654674806495),
 (612, 0.057353933467640436),
 (613, 0.01938916835823703),
 (614, 0.028676966733820218),
 (615, 0.029135827337403247),
 (616, 0.01938916835823703),
 (617, 0.14912022701586514),
 (618, 0.08371385281611447),
 (619, 0.0),
 (620, 0.0),
 (621, 0.051298917604257706),
 (622, 0.013710212427677042),
 (623, 0.015328483487124145),
 (624, 0.09428928580058928),
 (625, 0.04818694246524266),
 (626, 0.17920430732684967),
 (627, 0.08365931017628181),
 (628, 0.14273582042094193),
 (629, 0.028239124736245246),
 (630, 0.030386856273138196),
 (631, 0.034412360080584264),
 (632, 0.10147651372376074),
 (633, 0.11615078990692515),
 (634, 0.07664241743562072),
 (635, 0.09462916232627815),
 (636, 0.013809204416652685),
 (637, 0.030934411244487297),
 (638, 0.03934447376823168),
 (639, 0.015467205622243648),
 (640, 0.0402766210155791),
 (641, 0.0),
 (642, 0.14227759830611805),
 (643, 0.18560646746692377),
 (644, 0.029867384554474945),
 (645, 0.026669037353133248),
 (646, 0.06424925662032355),
 (647, 0.056055185467121044),
 (648, 0.016062314155080887),
 (649, 0.0),
 (650, 0.044801076831712416),
 (651, 0.0),
 (652, 0.02761840883330537),
 (653, 0.07543142864047142),
 (654, 0.06748819059987712),
 (655, 0.04682929057908469),
 (656, 0.014013796366780261),
 (657, 0.04521000789084244),
 (658, 0.039216523921200154),
 (659, 0.014808721943977306),
 (660, 0.10138838820672658),
 (661, 0.2838874869788344),
 (662, 0.0),
 (663, 0.0),
 (664, 0.03582871819500093),
 (665, 0.04370374100610487),
 (666, 0.10039117221153818),
 (667, 0.0),
 (668, 0.07755667343294811),
 (669, 0.020942695414584774),
 (670, 0.05967860100145693),
 (671, 0.056055185467121044),
 (672, 0.016731862035256364),
 (673, 0.03647702873143481),
 (674, 0.08278327231656524),
 (675, 0.0468292905790847),
 (676, 0.015756337291581362),
 (677, 0.08111071056538127),
 (678, 0.07647191129018724),
 (679, 0.0),
 (680, 0.16289594138375035),
 (681, 0.04966996338993915),
 (682, 0.012667364798453496),
 (683, 0.03012376165643889),
 (684, 0.04055535528269063),
 (685, 0.01967223688411584),
 (686, 0.056573571480353566),
 (687, 0.09832102880166932),
 (688, 0.040555355282690636),
 (689, 0.0),
 (690, 0.02445579940222592),
 (691, 0.044801076831712416),
 (692, 0.23475647508309563),
 (693, 0.015756337291581362),
 (694, 0.02488363008967197),
 (695, 0.04966996338993915),
 (696, 0.026315789473684206),
 (697, 0.0),
 (698, 0.043015450100730324),
 (699, 0.02341464528954235),
 (700, 0.015609763526361564),
 (701, 0.056573571480353566),
 (702, 0.012159009577144936),
 (703, 0.013518451760896878),
 (704, 0.09197090092274487),
 (705, 0.014686837386151166),
 (706, 0.014338483366910109),
 (707, 0.0),
 (708, 0.032124628310161774),
 (709, 0.053702161354105465),
 (710, 0.03627381250550058),
 (711, 0.032773676267223106),
 (712, 0.013809204416652685),
 (713, 0.048098607024388174),
 (714, 0.0),
 (715, 0.08111071056538126),

In [91]:
#sort on basis of similarity
sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])

[(0, 0.9999999999999998),
 (2409, 0.49356764739637354),
 (4336, 0.4113063728303113),
 (1537, 0.38807121827489494),
 (3162, 0.3879852850993631),
 (373, 0.380442955126341),
 (838, 0.3776782946782564),
 (2021, 0.3742636563667588),
 (1920, 0.35840861465369933),
 (305, 0.3421708589084696),
 (278, 0.3311330892662609),
 (300, 0.32481131806711666),
 (1082, 0.3248113180671166),
 (2204, 0.3247499344668203),
 (507, 0.3231104224953257),
 (158, 0.3222129681246328),
 (3538, 0.3162994973926084),
 (1216, 0.31264094565852313),
 (3736, 0.3121952705272313),
 (184, 0.30842358510917445),
 (577, 0.30588764516074896),
 (461, 0.30442954117128224),
 (1321, 0.3008967382970351),
 (47, 0.2987264917430253),
 (1715, 0.2974059387397313),
 (1071, 0.2949687762244818),
 (2970, 0.2938769068226293),
 (582, 0.29314232661238443),
 (1355, 0.29139711855430955),
 (260, 0.29135827337403253),
 (149, 0.2896811091620759),
 (1357, 0.28867513459481287),
 (4, 0.28791446098121787),
 (1204, 0.2867696673382022),
 (94, 0.2866297455600074),
 (778, 0.2845551966122361),
 (661, 0.2838874869788344),
 (539, 0.27912109783679506),
 (239, 0.2752988806446741),
 (972, 0.2678577339568831),
 (973, 0.2605842192811105),
 (1765, 0.2604940361258638),
 (1957, 0.26013299085723596),
 (61, 0.25958499574503335),
 (3675, 0.25605197407973057),
 (4048, 0.25391668753850405),
 (595, 0.25387276871303704),
 (95, 0.25362863675089403),
 (322, 0.2533558548547658),
 (56, 0.24722569302909875),
 (1201, 0.24722569302909872),
 (74, 0.24678382369818674),
 (2971, 0.2445579940222592),
 (541, 0.24366985862022406),
 (1056, 0.24309485018510557),
 (502, 0.24165972609347458),
 (1344, 0.24099009325151113),
 (1220, 0.24002133617819923),
 (432, 0.2364763257317293),
 (692, 0.23475647508309563),
 (3409, 0.2342460684935891),
 (770, 0.23366150977305886),
 (1965, 0.23366150977305886),
 (549, 0.23308661869922598),
 (2701, 0.23308661869922598),
 (581, 0.23288666826750604),
 (150, 0.22941573387056172),
 (52, 0.22790142204853647),
 (1996, 0.22663483432464554),
 (83, 0.22213082915965962),
 (754, 0.22213082915965962),
 (3147, 0.2204856030790368),
 (1373, 0.2204155075111935),
 (1089, 0.2176428750330035),
 (342, 0.21371260356627755),
 (41, 0.21341639745917707),
 (3999, 0.2130071614211525),
 (1278, 0.21179343552183932),
 (787, 0.21052631578947367),
 (91, 0.20991342856239587),
 (1982, 0.20991342856239584),
 (773, 0.2074364287612964),
 (236, 0.20561572340611634),
 (27, 0.20519567041703077),
 (230, 0.20441907985364974),
 (270, 0.20138310507789547),
 (1479, 0.20138310507789547),
 (1031, 0.20078234442307638),
 (228, 0.20073876713674155),
 (2938, 0.19927028533261387),
 (557, 0.19918863762856526),
 (168, 0.19664205760333864),
 (2547, 0.19619314913492367),
 (454, 0.19619314913492364),
 (3608, 0.19564639521780738),
 (4192, 0.19509974314292697),
 (67, 0.1946978894863169),
 (1488, 0.1938916835823703),
 (1329, 0.1908854288927333),
 (1656, 0.19001047197680243),
 (889, 0.1860807318911967),
 (643, 0.18560646746692377),
 (1297, 0.18560646746692377),
 (1496, 0.185539010998235),
 (1322, 0.1842105263157894),
 (3628, 0.18394180184548975),
 (4596, 0.1835325870964494),
 (1002, 0.1830104449656007),
 (1280, 0.18249909877210785),
 (480, 0.18074256993863336),
 (2333, 0.1792043073268497),
 (626, 0.17920430732684967),
 (306, 0.17914359097500465),
 (1285, 0.17875929966870285),
 (1668, 0.17844356324383875),
 (466, 0.17660431427533915),
 (1178, 0.17624204863381399),
 (579, 0.1749783098183389),
 (111, 0.17497830981833887),
 (2786, 0.17492785713532988),
 (2865, 0.17453202440084276),
 (2916, 0.17342199390482396),
 (4405, 0.1720618004029213),
 (87, 0.17099639201419237),
 (233, 0.17040572913692198),
 (249, 0.17040572913692198),
 (4343, 0.17036656890909552),
 (46, 0.17013926184468012),
 (2450, 0.17013926184468012),
 (1928, 0.16861331835836557),
 (35, 0.1675415633166782),
 (2787, 0.16747265870207706),
 (3072, 0.16747265870207706),
 (931, 0.16747265870207703),
 (3730, 0.16742770563222895),
 (1383, 0.16692446522239715),
 (141, 0.16556654463313047),
 (223, 0.16556654463313047),
 (2235, 0.16531163063339513),
 (1560, 0.1642706150496122),
 (26, 0.16427061504961218),
 (3327, 0.16390251702679645),
 (4114, 0.16386838133611553),
 (564, 0.1630554699247529),
 (680, 0.16289594138375035),
 (855, 0.16222142113076254),
 (2439, 0.16222142113076252),
 (108, 0.1615552112476628),
 (200, 0.16122923187750418),
 (1275, 0.16122923187750418),
 (2515, 0.16122923187750418),
 (4664, 0.16122923187750418),
 (843, 0.16062314155080884),
 (3218, 0.15974461276617435),
 (942, 0.1590711907439444),
 (1083, 0.15897016107942197),
 (36, 0.15897016107942194),
 (222, 0.15806712450288418),
 (2556, 0.15789473684210523),
 (14, 0.1577233170360112),
 (4468, 0.15756337291581363),
 (1396, 0.15650535813672986),
 (2820, 0.15650535813672986),
 (3449, 0.1556357543698668),
 (2584, 0.15511334686589623),
 (1444, 0.15452877499092174),
 (101, 0.1541517600345829),
 (229, 0.1538057703910978),
 (2022, 0.15301409312053071),
 (3431, 0.15242624470826976),
 (2059, 0.15193428136569098),
 (2999, 0.15174424466672098),
 (1774, 0.15086285728094284),
 (401, 0.15058675831730728),
 (2902, 0.15018785229652767),
 (156, 0.14975189244419534),
 (2676, 0.14933692277237473),
 (1109, 0.14930178053803184),
 (1361, 0.14930178053803184),
 (617, 0.14912022701586514),
 (1466, 0.14910501299480672),
 (2789, 0.14886458551295736),
 (1883, 0.14870296936986566),
 (31, 0.14808721943977307),
 (740, 0.14768094372379),
 (1097, 0.14748154320250398),
 (2762, 0.14748154320250398),
 (1446, 0.14686837386151166),
 (3630, 0.14686837386151166),
 (529, 0.14599927901768628),
 (1037, 0.14599927901768628),
 (3188, 0.14567913668701624),
 (1379, 0.14552644042288465),
 (3755, 0.14456082739572798),
 (127, 0.14429582107316452),
 (5, 0.1433848336691011),
 (3819, 0.14316407166954997),
 (628, 0.14273582042094193),
 (642, 0.14227759830611805),
 (1570, 0.14180703562423225),
 (2209, 0.14180703562423225),
 (2347, 0.14180703562423225),
 (800, 0.14159846508095772),
 (2075, 0.14159846508095772),
 (2731, 0.14159846508095772),
 (4353, 0.1404878717372541),
 (483, 0.1399422857082639),
 (1756, 0.1399422857082639),
 (1294, 0.1391037210186643),
 (2003, 0.1391037210186643),
 (232, 0.13834289277321493),
 (3212, 0.13834289277321493),
 (587, 0.13809204416652687),
 (2058, 0.13770565818881086),
 (2135, 0.13767219793848368),
 (365, 0.13685996549319585),
 (1741, 0.13685996549319585),
 (3959, 0.13679711361135388),
 (110, 0.1361331925293325),
 (1658, 0.13572417850765922),
 (1166, 0.1357241785076592),
 (1831, 0.13555692745397502),
 (1649, 0.13530201829834765),
 (490, 0.13497638119975425),
 (3728, 0.13497638119975425),
 (4545, 0.13450689671224256),
 (169, 0.1343320988518935),
 (1019, 0.13425540338526365),
 (505, 0.13382584475782766),
 (2169, 0.13245323570650439),
 (3235, 0.13245323570650439),
 (755, 0.13245323570650436),
 (1015, 0.13245323570650436),
 (878, 0.132005000120825),
 (2760, 0.13111122301831463),
 (220, 0.13109470506889243),
 (1589, 0.13109470506889243),
 (18, 0.13006649542861798),
 (2656, 0.13006649542861798),
 (473, 0.13006649542861795),
 (3291, 0.12977713690461),
 (456, 0.1290564332299168),
 (2543, 0.1290564332299168),
 (939, 0.128920512778062),
 (2763, 0.12811501208373438),
 (1418, 0.12804983847550624),
 (72, 0.12725695259515554),
 (1161, 0.12725695259515554),
 (2247, 0.12725695259515554),
 (495, 0.12695834376925205),
 (267, 0.12695834376925202),
 (1445, 0.12667364798453495),
 (3443, 0.12612416730102238),
 (3195, 0.12565617248750865),
 (151, 0.12540051368250324),
 (279, 0.1251933489167979),
 (207, 0.12519334891679787),
 (2488, 0.12487810821089251),
 (2940, 0.12369267399882333),
 (208, 0.12361284651454937),
 (3905, 0.1233919118490934),
 (1529, 0.12313775728090239),
 (1191, 0.12297974198582043),
 (1498, 0.12227899701112961),
 (3117, 0.1222789970111296),
 (430, 0.1216660658480719),
 (1421, 0.1216660658480719),
 (3556, 0.12166606584807188),
 (362, 0.12105003117656304),
 (870, 0.12082986304673729),
 (3441, 0.12082986304673729),
 (487, 0.11980845957463077),
 (138, 0.11969747440993465),
 (275, 0.11969747440993464),
 (3821, 0.11969747440993464),
 (785, 0.11959121830873498),
 (1793, 0.11946953821789978),
 (2035, 0.11946953821789978),
 (1802, 0.11920791213585391),
 (419, 0.11846977555181845),
 (1938, 0.11846977555181845),
 (2918, 0.11846977555181845),
 (3572, 0.11846977555181845),
 (4325, 0.11846977555181845),
 (568, 0.1183892660110542),
 (1721, 0.11838926601105419),
 (2732, 0.11768778828946262),
 (102, 0.11764957176360048),
 (363, 0.11764957176360048),
 (1299, 0.11764957176360047),
 (53, 0.11764957176360046),
 (1018, 0.11749469908920933),
 (3756, 0.11717498502967603),
 (70, 0.11712303424679454),
 (7, 0.11654330934961299),
 (536, 0.11654330934961299),
 (3615, 0.1164681928033949),
 (633, 0.11615078990692515),
 (589, 0.11615078990692514),
 (592, 0.11615078990692514),
 (1293, 0.11589658124319134),
 (172, 0.11589658124319133),
 (2888, 0.11566778213857246),
 (1467, 0.11561466260321597),
 (4316, 0.11561466260321597),
 (256, 0.11470786693528087),
 (1411, 0.11470786693528087),
 (2239, 0.11470786693528087),
 (3314, 0.11470786693528087),
 (215, 0.11470786693528086),
 (1617, 0.11382207864489444),
 (459, 0.11314714296070713),
 (2284, 0.11295649894498098),
 (1194, 0.11295649894498097),
 (147, 0.11243619908556621),
 (1929, 0.11243619908556621),
 (4178, 0.11194341570991126),
 (3770, 0.11164843913471803),
 (3622, 0.11134983352076111),
 (4230, 0.11134983352076111),
 (311, 0.1113498335207611),
 (1092, 0.1113498335207611),
 (4100, 0.111323406598941),
 (1897, 0.11128297681493145),
 (784, 0.11128297681493143),
 (107, 0.1106817677872384),
 (2133, 0.11047363533322149),
 (2001, 0.11047363533322148),
 (1501, 0.11037769642208697),
 (3781, 0.11037769642208697),
 (10, 0.11029436104106954),
 (4512, 0.11029436104106954),
 (794, 0.11029436104106953),
 (462, 0.11024280153951839),
 (389, 0.11020775375559674),
 (3181, 0.11020775375559674),
 (1101, 0.10968169942141634),
 (185, 0.10926834468453095),
 (413, 0.10926834468453095),
 (1614, 0.10926834468453095),
 (2718, 0.10882143751650175),
 (476, 0.10838874619051497),
 (3378, 0.10838874619051497),
 (3721, 0.10838874619051497),
 (4473, 0.10838874619051497),
 (1039, 0.10827043935570554),
 (3354, 0.10827043935570553),
 (599, 0.10814761408717502),
 (2796, 0.10814761408717502),
 (2873, 0.10814761408717502),
 (2880, 0.10814761408717502),
 (4097, 0.10814761408717502),
 (17, 0.108147614087175),
 (813, 0.108147614087175),
 (1828, 0.108147614087175),
 (1474, 0.1074861545850028),
 (1439, 0.10740432270821092),
 (585, 0.10729938440986901),
 (1749, 0.10729938440986901),
 (2072, 0.10729938440986901),
 (3810, 0.10715994395536395),
 (571, 0.10705186531570646),
 (2498, 0.10667614941253299),
 (1171, 0.10650358071057624),
 (2323, 0.10650358071057624),
 (790, 0.1064809179630677),
 (997, 0.1064809179630677),
 (371, 0.10635399695598369),
 (3498, 0.10635399695598369),
 (980, 0.10619884881071828),
 (2990, 0.10619884881071828),
 (1574, 0.10591900946051636),
 (1639, 0.10526315789473682),
 (4010, 0.10526315789473682),
 (3008, 0.10495671428119792),
 (3518, 0.10495671428119792),
 (2456, 0.10471347707292387),
 (3159, 0.10471347707292386),
 (768, 0.10457739712320041),
 (1898, 0.1039048666932262),
 (3102, 0.1037571695799112),
 (3764, 0.1037571695799112),
 (4731, 0.1037571695799112),
 (422, 0.10375716957991118),
 (4602, 0.10375716957991118),
 (900, 0.10366105360784116),
 (16, 0.10366105360784114),
 (4694, 0.10366105360784114),
 (206, 0.1032370802417528),
 (412, 0.10280786170305815),
 (166, 0.10259783520851543),
 (329, 0.10259783520851541),
 (404, 0.10259783520851541),
 (1113, 0.10259783520851541),
 (1768, 0.10259783520851541),
 (3537, 0.10259783520851541),
 (1042, 0.1025978352085154),
 (2480, 0.1025978352085154),
 (4587, 0.1025978352085154),
 (2901, 0.10197539568091137),
 (187, 0.10147651372376074),
 (632, 0.10147651372376074),
 (660, 0.10138838820672658),
 (1524, 0.10138838820672658),
 (1942, 0.10138838820672658),
 (2506, 0.10138838820672658),
 (3376, 0.10138838820672658),
 (3716, 0.10138838820672658),
 (3022, 0.10133891838762797),
 (814, 0.10116282977781398),
 (3910, 0.10116282977781396),
 (420, 0.1007265930331758),
 (330, 0.10039117221153819),
 (400, 0.10039117221153819),
 (2181, 0.10039117221153819),
 (666, 0.10039117221153818),
 (9, 0.10036938356837077),
 (1273, 0.10036938356837077),
 (3414, 0.10036938356837077),
 (1512, 0.10036938356837076),
 (586, 0.10012523486435176),
 (4276, 0.10012523486435176),
 (4348, 0.10012523486435176),
 (1274, 0.09984038297885897),
 (2053, 0.09984038297885897),
 (3093, 0.09959431881428264),
 (48, 0.09959431881428263),
 (1531, 0.09959431881428263),
 (51, 0.09895413919905867),
 (253, 0.09895413919905867),
 (2120, 0.0983611844205792),
 (3663, 0.0983611844205792),
 (4256, 0.0983611844205792),
 (687, 0.09832102880166932),
 (1034, 0.09832102880166932),
 (1237, 0.09832102880166932),
 (30, 0.09809657456746182),
 (4079, 0.09733285267845751),
 (935, 0.09694584179118515),
 (1158, 0.09694584179118515),
 (2634, 0.09694584179118515),
 (3661, 0.09694584179118515),
 (246, 0.09673016668133488),
 (271, 0.09637388493048532),
 (524, 0.09637388493048532),
 (793, 0.09637388493048532),
 (3935, 0.09637388493048532),
 (4205, 0.09637388493048532),
 (1678, 0.09619721404877635),
 (174, 0.09597148699373931),
 (1878, 0.09597148699373931),
 (4600, 0.0959714869937393),
 (897, 0.09567297464698797),
 (2178, 0.09567297464698797),
 (2297, 0.09567297464698797),
 (4165, 0.09567297464698797),
 (4333, 0.09567297464698797),
 (4368, 0.09567297464698797),
 (33, 0.09558988911273406),
 (1068, 0.09558988911273406),
 (2868, 0.09558988911273406),
 (3289, 0.09558988911273406),
 (4000, 0.09558988911273406),
 (4236, 0.09558988911273406),
 (859, 0.09544271444636666),
 (1086, 0.09544271444636666),
 (1824, 0.09544271444636666),
 (2444, 0.09544271444636666),
 (1324, 0.09544271444636665),
 (3418, 0.09544271444636665),
 (1414, 0.09529323477053277),
 (2054, 0.09529323477053275),
 (3464, 0.09529323477053275),
 (123, 0.09464970485606018),
 (635, 0.09462916232627815),
 (3174, 0.09462916232627815),
 (2158, 0.09453802374948818),
 (39, 0.09453802374948816),
 (438, 0.09453802374948816),
 (1363, 0.09453802374948816),
 (3037, 0.09453802374948816),
 (2448, 0.09431035367836321),
 (294, 0.09428928580058928),
 (624, 0.09428928580058928),
 (531, 0.09397878236968457),
 (1673, 0.0936585811581694),
 (312, 0.09365858115816939),
 (3450, 0.09365858115816939),
 (129, 0.09334163073596637),
 (217, 0.09334163073596637),
 (4154, 0.09334163073596637),
 (307, 0.09308574042571362),
 (122, 0.09304036594559835),
 (1047, 0.09304036594559835),
 (334, 0.09280323373346189),
 (1362, 0.09280323373346189),
 (1565, 0.09280323373346189),
 (2528, 0.09280323373346189),
 (1233, 0.09271726499455304),
 (1858, 0.09222859518214328),
 (704, 0.09197090092274487),
 (988, 0.09197090092274487),
 (4538, 0.09197090092274487),
 (4777, 0.09197090092274487),
 (4341, 0.09197090092274486),
 (1306, 0.09183979479633063),
 (1884, 0.09183979479633061),
 (1005, 0.0917662935482247),
 (1327, 0.0917662935482247),
 (1655, 0.0917662935482247),
 (1745, 0.09176629354822469),
 (304, 0.09154684414630487),
 (2834, 0.09150522248280035),
 (238, 0.09131087488821056),
 (1823, 0.09116056881941459),
 (2642, 0.09116056881941459),
 (2696, 0.09116056881941459),
 (2023, 0.09091675835657292),
 (812, 0.09089518086526238),
 (2598, 0.09086217008485094),
 (3201, 0.09086217008485092),
 (105, 0.09068453126375145),
 (1833, 0.09068453126375145),
 (2396, 0.09068453126375145),
 (1623, 0.09037128496931668),
 (3909, 0.09037128496931668),
 (2433, 0.09033950326094177),
 (418, 0.0899842541331695),
 (1782, 0.0899842541331695),
 (3982, 0.0899842541331695),
 (4026, 0.0899842541331695),
 (1098, 0.08977310580745097),
 (1808, 0.08960215366342483),
 (2740, 0.08960215366342483),
 (449, 0.08957179548750233),
 (1843, 0.08957179548750233),
 (1927, 0.08957179548750233),
 (2378, 0.08957179548750233),
 (4789, 0.08921722983855178),
 (532, 0.08918325397005952),
 (2713, 0.08885233166386385),
 (3309, 0.08885233166386385),
 (3553, 0.08885233166386385),
 (513, 0.08885233166386383),
 (1700, 0.08885233166386383),
 (1701, 0.08885233166386383),
 (2914, 0.08885233166386383),
 (131, 0.08849904067559858),
 (320, 0.08849904067559858),
 (744, 0.08849904067559858),
 (1004, 0.08849904067559858),
 (1519, 0.08849904067559858),
 (4650, 0.08849904067559858),
 (1575, 0.08830215713766958),
 (3954, 0.08830215713766958),
 (4654, 0.08830215713766958),
 (2291, 0.08820139006486122),
 (1516, 0.08813576890402881),
 (43, 0.08812102431690699),
 (1064, 0.08812102431690699),
 (2644, 0.08812102431690699),
 (2898, 0.08812102431690699),
 (775, 0.08746392856766494),
 (1585, 0.08746392856766494),
 (2496, 0.08746392856766494),
 (4339, 0.08746392856766494),
 (535, 0.08740748201220974),
 (3066, 0.08740748201220974),
 (1497, 0.08709270531385191),
 (2243, 0.08671099695241198),
 (4558, 0.08671099695241198),
 (491, 0.08658487179917634),
 (731, 0.08646430798325933),
 (4657, 0.08646430798325933),
 (1452, 0.08608581939007431),
 (752, 0.08603090020146066),
 (777, 0.08603090020146066),
 (1632, 0.08603090020146066),
 (1340, 0.08603090020146065),
 (4279, 0.08603090020146065),
 (1103, 0.08559529790779072),
 (37, 0.08549819600709618),
 (86, 0.08549819600709618),
 (203, 0.08549819600709618),
 (472, 0.08549819600709618),
 (764, 0.08549819600709618),
 (3710, 0.08549819600709618),
 (4110, 0.08549819600709618),
 (192, 0.08536655898367082),
 (728, 0.08536655898367082),
 (1195, 0.08536655898367082),
 (1301, 0.08536655898367082),
 (2968, 0.08536655898367082),
 (3206, 0.08536655898367082),
 (319, 0.08520286456846099),
 (808, 0.08520286456846099),
 (2114, 0.08520286456846099),
 (2161, 0.08520286456846099),
 (2674, 0.08520286456846099),
 (3709, 0.08520286456846099),
 (301, 0.08511306704001456),
 (75, 0.08456376143646728),
 (2583, 0.08456376143646728),
 (2636, 0.08456376143646728),
 (125, 0.08433490104000932),
 (4453, 0.08408277820068158),
 (170, 0.08408277820068157),
 (1832, 0.08408277820068155),
 (1240, 0.0837707816583391),
 (2579, 0.0837707816583391),
 (2976, 0.0837707816583391),
 (4198, 0.0837707816583391),
 (4611, 0.0837707816583391),
 (809, 0.08371385281611449),
 (618, 0.08371385281611447),
 (3344, 0.08371385281611447),
 (2093, 0.08365931017628182),
 (2686, 0.08365931017628182),
 (4673, 0.08365931017628182),
 (341, 0.08365931017628181),
 (627, 0.08365931017628181),
 (853, 0.08365931017628181),
 (2471, 0.08365931017628181),
 (3542, 0.08365931017628181),
 (182, 0.08346223261119859),
 (1011, 0.08346223261119859),
 (2527, 0.08346223261119858),
 (3634, 0.08346223261119858),
 (4181, 0.08346223261119858),
 (360, 0.08326256191221612),
 (3607, 0.08326256191221612),
 (63, 0.08285522649991611),
 (1534, 0.08285522649991611),
 (3881, 0.08285522649991611),
 (4068, 0.08285522649991611),
 (4506, 0.08285522649991611),
 (674, 0.08278327231656524),
 (1096, 0.08278327231656524),
 (1465, 0.08278327231656524),
 (2060, 0.08278327231656524),
 (3028, 0.08278327231656524),
 (4042, 0.08278327231656524),
 (2652, 0.08240856434303291),
 (4184, 0.08240856434303291),
 (103, 0.08226127456606226),
 (862, 0.08226127456606226),
 (3389, 0.08226127456606225),
 (71, 0.08193419066805777),
 (510, 0.08193419066805777),
 (556, 0.08193419066805777),
 (898, 0.08193419066805777),
 (2148, 0.08193419066805777),
 (2817, 0.08193419066805777),
 (3926, 0.08193419066805777),
 (4006, 0.08193419066805777),
 (4640, 0.08193419066805777),
 (1168, 0.08167991551759951),
 (1289, 0.08167991551759951),
 (1908, 0.08152773496237643),
 (677, 0.08111071056538127),
 (112, 0.08111071056538126),
 (332, 0.08111071056538126),
 (333, 0.08111071056538126),
 (506, 0.08111071056538126),
 (715, 0.08111071056538126),
 (1401, 0.08111071056538126),
 (2017, 0.08111071056538126),
 (2270, 0.08111071056538126),
 (2311, 0.08111071056538126),
 (3769, 0.08111071056538126),
 (4636, 0.08111071056538126),
 (448, 0.0805532420311582),
 (2392, 0.0805532420311582),
 (4249, 0.0805532420311582),
 (82, 0.08031157077540443),
 (3874, 0.08031157077540443),
 (4280, 0.08031157077540443),
 (85, 0.08017658293783157),
 (1426, 0.08000711205939974),
 (4206, 0.07987230638308718),
 (4355, 0.07987230638308718),

In [92]:
def recommend (movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]

    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [99]:
recommend('Tangled')

The Princess and the Frog
Enchanted
Into the Woods
Pocahontas
Happily N'Ever After